services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: risk-db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  data-service:
    image: thesis-example-data-service
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/risk-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      RISK_SERVICE_URL: http://risk-service:8080/process

  risk-service:
    image: thesis-example-risk-service
    depends_on:
      - db
      - data-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/risk-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  web-service:
    image: thesis-example-web-service
    depends_on:
      - db
      - risk-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/risk-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass