components:

  - name: "service-a"
    provides:
      interfaceType: HTTP_API
    dependencies:
      - type: HTTP_API
        target: "service-c"
        targetUrlEnv: COUNTER_URL
      - type: JDBC
        target: "db"
        targetUrlEnv: SPRING_DATASOURCE_URL

  - name: "service-b"
    provides:
      interfaceType: HTTP_API
    dependencies:
      - type: JDBC
        target: "db"
        targetUrlEnv: SPRING_DATASOURCE_URL

  - name: "service-c"
    provides:
      interfaceType: HTTP_API

  - name: "db"
    provides:
      interfaceType: DATABASE
