components:

  - name: "service-a"
    provides:
      interfaceType: HTTP
    requires:
      - type: HTTP
        target: "service-c"
        targetUrlEnv: COUNTER_URL
      - type: JDBC
        target: "db"
        targetUrlEnv: SPRING_DATASOURCE_URL
        usernameEnv: SPRING_DATASOURCE_USERNAME
        passwordEnv: SPRING_DATASOURCE_PASSWORD

  - name: "service-b"
    provides:
      interfaceType: HTTP
    requires:
      - type: JDBC
        target: "db"
        targetUrlEnv: SPRING_DATASOURCE_URL
        usernameEnv: SPRING_DATASOURCE_USERNAME
        passwordEnv: SPRING_DATASOURCE_PASSWORD

  - name: "service-c"
    provides:
      interfaceType: HTTP

  - name: "db"
    provides:
      interfaceType: DATABASE
