version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: pieker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pieker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: